#!/bin/sh

#
# generate some own corpus, which is bigger then Silesia
#

U=""

# Silesia compression corpus
# type: various
U="$U http://sun.aei.polsl.pl/~sdeor/corpus/silesia.zip"

# Chromium v60
# type: binary
U="$U https://github.com/henrypp/chromium/releases/download/v60.0.3073.0-r464874-win32/chromium-sync.zip"

# Wikipedia stuff / documentation
# type: multimedia
U="$U https://dumps.wikimedia.org/archive/2002/2002-04-18/vikio-docs.tar.gz"

# Wikipedia Dump
# type: sql
U="$U https://dumps.wikimedia.org/archive/2002/2002-04-18/wikipedia_dump_20020321.sql.gz"

# Linux Kernel v2.6.0
# type: text/code
U="$U https://www.kernel.org/pub/linux/kernel/v2.6/linux-2.6.0.tar.xz"

# International Human Genome Project, chromosome #1
# type: text/dna
U="$U http://hgdownload.cse.ucsc.edu/goldenPath/hg18/chromosomes/chr1.fa.gz"

# Cisco Umbrella Popularity List, http://s3-us-west-1.amazonaws.com/umbrella-static/index.html
# type: text/urls
U="$U http://s3-us-west-1.amazonaws.com/umbrella-static/top-1m-2017-03-08.csv.zip"

# download corpus content
for url in $U; do
  F=`basename $url`
  test -f "$F" || wget "$url"
done

# build some nice tar, which can be used as single file on windows for testing
rm -rf mcorpus
mkdir mcorpus || exit
cd mcorpus
unzip ../top-1m-2017-03-08.csv.zip
unzip ../silesia.zip
unzip ../chromium-sync.zip
zcat ../chr1.fa.gz > chr1.fa
zcat ../vikio-docs.tar.gz | tar x
zcat ../wikipedia_dump_20020321.sql.gz > wikipedia_dump_20020321.sql
xzcat ../linux-2.6.0.tar.xz | tar x
find linux-2.6.0 -type f -exec cat {} > linux \;
rm -rf linux-2.6.0
cd ..

# name: mcorpus.tar
# bytes: 1249361920
tar cvf mcorpus.tar mcorpus
