#!/bin/sh

###########################################################################
# This script will generate an own corpus which contains:
# - Silesia compression corpus
# - the enwik8 corpus of the Large Text Compression Benchmark
# - chromosome #1 of the International Human Genome Project
#
# ctime: /TR 2025-12-31
###########################################################################
U=""

# Silesia compression corpus
# type: various
U="$U http://sun.aei.polsl.pl/~sdeor/corpus/silesia.zip"

# enwik8.zip, 100MB english text
# type: text/articles
# U="$U https://mattmahoney.net/dc/enwik8.zip"

# download corpus content
for url in $U; do
  F=`basename $url`
  test -f "$F" || wget "$url"
done

# cleanup
rm -rf mcorpus mcorpus.bin
mkdir mcorpus || exit
cd mcorpus

echo "Decompressing..."
unzip ../silesia.zip
#unzip ../enwik8.zip

# build one single file
echo "Putting the data together to mcorpus.bin..."
find . -type f -print0 | sort -z | xargs -r0 cat >> ../mcorpus.bin
cd ..
